-- Demo catalog. Every movie, person, cinema and bank is fictional.
-- Release dates are relative to the day this migration runs, so "Now Showing"
-- and "Coming Soon" start out correct on a fresh database.

insert into cities (id, name, icon, popular, sort_order) values
    ('mumbai', 'Mumbai', 'arch', true, 1),
    ('delhi-ncr', 'Delhi-NCR', 'gate', true, 2),
    ('bengaluru', 'Bengaluru', 'palace', true, 3),
    ('hyderabad', 'Hyderabad', 'minar', true, 4),
    ('chennai', 'Chennai', 'temple', true, 5),
    ('kolkata', 'Kolkata', 'bridge', true, 6),
    ('pune', 'Pune', 'fort', true, 7),
    ('kochi', 'Kochi', 'net', true, 8),
    ('ahmedabad', 'Ahmedabad', 'stepwell', true, 9),
    ('goa', 'Goa', 'waves', true, 10),
    ('agra', 'Agra', null, false, 100),
    ('amritsar', 'Amritsar', null, false, 100),
    ('bhopal', 'Bhopal', null, false, 100),
    ('bhubaneswar', 'Bhubaneswar', null, false, 100),
    ('chandigarh', 'Chandigarh', null, false, 100),
    ('coimbatore', 'Coimbatore', null, false, 100),
    ('dehradun', 'Dehradun', null, false, 100),
    ('guwahati', 'Guwahati', null, false, 100),
    ('indore', 'Indore', null, false, 100),
    ('jaipur', 'Jaipur', null, false, 100),
    ('kozhikode', 'Kozhikode', null, false, 100),
    ('lucknow', 'Lucknow', null, false, 100),
    ('madurai', 'Madurai', null, false, 100),
    ('mangaluru', 'Mangaluru', null, false, 100),
    ('mysuru', 'Mysuru', null, false, 100),
    ('nagpur', 'Nagpur', null, false, 100),
    ('nashik', 'Nashik', null, false, 100),
    ('patna', 'Patna', null, false, 100),
    ('puducherry', 'Puducherry', null, false, 100),
    ('raipur', 'Raipur', null, false, 100),
    ('ranchi', 'Ranchi', null, false, 100),
    ('surat', 'Surat', null, false, 100),
    ('thiruvananthapuram', 'Thiruvananthapuram', null, false, 100),
    ('tiruchirappalli', 'Tiruchirappalli', null, false, 100),
    ('udaipur', 'Udaipur', null, false, 100),
    ('vadodara', 'Vadodara', null, false, 100),
    ('varanasi', 'Varanasi', null, false, 100),
    ('vijayawada', 'Vijayawada', null, false, 100),
    ('visakhapatnam', 'Visakhapatnam', null, false, 100);

-- Eight cinema chains; popular cities get all eight, the rest get the first three.
with chains (idx, name, mall, amenities, formats, screens, distance) as (values
    (1, 'Marquee Cinemas', 'Palladium Arcade', 'parking,food,wheelchair', '2D,3D,IMAX', 3, 2.1),
    (2, 'Reelhouse', 'Infinity Walk', 'parking,food,wheelchair', '2D,3D,4DX', 4, 4.8),
    (3, 'Silverscreen Picturehouse', '', 'food', '2D', 5, 3.2),
    (4, 'Orion Multiplex', 'Lakeside', 'parking,food,wheelchair', '2D,3D,IMAX,4DX', 6, 7.9),
    (5, 'Moonlight Talkies', '', 'wheelchair', '2D', 7, 1.4),
    (6, 'Aurora Screens', 'Viviana Square', 'parking,food,wheelchair', '2D,3D,IMAX', 3, 18.6),
    (7, 'Balcony Box Cinemas', '', 'parking,food', '2D,3D', 4, 6.3),
    (8, 'Cinéport', 'Oberoi Link', 'parking,food,wheelchair', '2D,4DX', 5, 9.1)
), areas (city_id, names) as (values
    ('mumbai', array['Lower Parel', 'Andheri West', 'Bandra West', 'Powai', 'Dadar East', 'Thane West', 'Juhu', 'Goregaon East']),
    ('bengaluru', array['Koramangala', 'Indiranagar', 'Whitefield', 'Jayanagar', 'Malleshwaram', 'HSR Layout', 'Hebbal', 'Rajajinagar']),
    ('delhi-ncr', array['Saket', 'Connaught Place', 'Vasant Kunj', 'Noida Sector 18', 'Gurugram Cyber Hub', 'Rajouri Garden', 'Dwarka', 'Nehru Place']),
    ('hyderabad', array['Banjara Hills', 'Gachibowli', 'Kukatpally', 'Ameerpet', 'Madhapur', 'Kondapur', 'Dilsukhnagar', 'Begumpet']),
    ('chennai', array['Velachery', 'T. Nagar', 'Anna Nagar', 'OMR', 'Vadapalani', 'Guindy', 'Porur', 'Adyar']),
    ('kolkata', array['Salt Lake', 'Park Street', 'New Town', 'Gariahat', 'Howrah', 'Ballygunge', 'Behala', 'Dum Dum']),
    ('pune', array['Koregaon Park', 'Viman Nagar', 'Baner', 'Kothrud', 'Hinjewadi', 'Camp', 'Aundh', 'Hadapsar']),
    ('kochi', array['Edappally', 'Kakkanad', 'MG Road', 'Vyttila', 'Kaloor', 'Panampilly Nagar', 'Aluva', 'Fort Kochi']),
    ('ahmedabad', array['SG Highway', 'Prahlad Nagar', 'Navrangpura', 'Vastrapur', 'Satellite', 'Bodakdev', 'Maninagar', 'Chandkheda']),
    ('goa', array['Panaji', 'Margao', 'Mapusa', 'Porvorim', 'Vasco', 'Calangute', 'Ponda', 'Candolim'])
), all_areas as (
    select c.id as city_id, coalesce(a.names, array['Central', 'Old Town', 'Station Road']) as names
    from cities c left join areas a on a.city_id = c.id
)
insert into cinemas (city_id, name, chain, area, distance_km, amenities, formats, screens)
select aa.city_id,
       case when ch.mall = '' then ch.name else ch.name || ': ' || ch.mall end,
       ch.name, aa.names[ch.idx], ch.distance, ch.amenities, ch.formats, ch.screens
from all_areas aa
join chains ch on ch.idx <= array_length(aa.names, 1)
order by aa.city_id, ch.idx;

insert into movies (id, title, certificate, runtime_minutes, genres, languages, formats, release_date, status, rating, votes, synopsis, trailer_url, featured_rank, art_motif, art_kicker, art_poster_lines, art_palette) values
    ('monsoon-protocol', 'Monsoon Protocol', 'UA', 148, 'Action,Thriller', 'Hindi,English,Tamil,Telugu', '2D,IMAX,4DX', current_date - 16, 'NOW_SHOWING', 8.7, '48.2K',
     'When Mumbai''s biggest storm in a century knocks out the city grid, a suspended crime-branch officer has one night to stop a crew planning to empty a bank vault under cover of the flood.',
     null, 2, 'rain', 'A ROHAN KAPADIA FILM', 'Monsoon,Protocol', '#0b2533,#12404f,#ffc53d'),
    ('orbit-of-ashes', 'Orbit of Ashes', 'UA', 162, 'Sci-Fi,Adventure', 'English,Hindi,Tamil', '2D,3D,IMAX,4DX', current_date - 9, 'NOW_SHOWING', 9.1, '61.5K',
     'Twelve years after Earth''s last colony ship went silent, a salvage pilot answers a distress call from its orbit — and finds the crew has been waiting for her, by name.',
     null, 1, 'orbit', 'IN IMAX · 3D · 4DX', 'Orbit of,Ashes', '#170b07,#4a1c0c,#ff8a4c'),
    ('iravu-vettai', 'Iravu Vettai', 'A', 141, 'Action,Crime', 'Tamil,Telugu,Hindi', '2D,IMAX', current_date - 23, 'NOW_SHOWING', 8.4, '29.7K',
     'A night-shift ambulance driver in Madurai becomes the only witness to a murder — and the killers know exactly which route he drives.',
     null, 4, 'eyes', 'NIGHT HUNT', 'Iravu,Vettai', '#0c0606,#3a0b0a,#ff5b45'),
    ('chandamama-express', 'Chandamama Express', 'U', 132, 'Comedy,Family', 'Telugu,Hindi,Kannada', '2D', current_date - 2, 'NOW_SHOWING', 8.1, '12.3K',
     'Three generations of one loud family squeeze into a single sleeper coach for a cousin''s wedding in Vizag. Nothing — the luggage, the gossip, or the groom — arrives on time.',
     null, null, 'train', 'THE WHOLE FAMILY IS COMING', 'Chandamama,Express', '#0d1a40,#1d3570,#ffd36b'),
    ('hampi-nights', 'Hampi Nights', 'UA', 127, 'Romance,Drama', 'Kannada,English', '2D', current_date - 9, 'NOW_SHOWING', 7.9, '8.4K',
     'An architect restoring a ruined mandapa and a boulder-climbing guide argue about everything — until a monsoon washes out the only road home.',
     null, null, 'ruins', 'STONE. SUN. STORM.', 'Hampi,Nights', '#4a200e,#a14a22,#ffc27a'),
    ('kaayal-kinavu', 'Kaayal Kinavu', 'UA', 138, 'Drama,Mystery', 'Malayalam,Tamil', '2D', current_date - 16, 'NOW_SHOWING', 8.9, '15.1K',
     'A houseboat cook in Alappuzha finds an old reel of film hidden in the hull — footage of a village that, according to every map, never existed.',
     null, 3, 'palms', 'BACKWATER DREAM', 'Kaayal,Kinavu', '#04201c,#0b4a3e,#8fe0c6'),
    ('the-last-projectionist', 'The Last Projectionist', 'U', 118, 'Drama', 'English,Hindi', '2D', current_date - 23, 'NOW_SHOWING', 8.6, '9.8K',
     'On the final night before a single-screen cinema in Kolkata is demolished, its 71-year-old projectionist decides to screen one last film — the one he has refused to show for forty years.',
     null, null, 'beam', 'ONE LAST SHOW', 'The Last,Projectionist', '#15100b,#3d2c1c,#ffe2a8'),
    ('haveli-no-13', 'Haveli No. 13', 'UA', 131, 'Horror,Comedy', 'Hindi', '2D,4DX', current_date - 2, 'NOW_SHOWING', 7.6, '18.9K',
     'Two broke YouTubers rent a "haunted" Jaipur haveli for a viral ghost hunt. The ghosts are real. They also want 40% of the ad revenue.',
     null, null, 'haveli', 'NOW WITH 4DX CHILLS', 'Haveli,No. 13', '#0b1510,#1f3a26,#c8f25a'),
    ('samudra-manthan-part-one', 'Samudra Manthan: Part One', 'UA', 171, 'Mythology,Action', 'Hindi,Telugu,Tamil,Kannada,Malayalam', '2D,3D,IMAX', current_date + 19, 'COMING_SOON', null, '84.2K',
     'Gods and asuras strike a fragile truce to churn the cosmic ocean for the nectar of immortality — and one ferryman is caught between them.',
     null, null, 'waves', 'THE CHURNING BEGINS', 'Samudra,Manthan', '#03101c,#0a3352,#ffc53d'),
    ('tokyo-tiffin', 'Tokyo Tiffin', 'U', 104, 'Animation,Family', 'English,Hindi,Tamil', '2D,3D', current_date + 33, 'COMING_SOON', null, '21.7K',
     'A dabbawala''s daughter wins a trip to Tokyo and sets out to deliver one very special lunch box across a city of fourteen million.',
     null, null, 'tiffin', 'DELIVERY GUARANTEED', 'Tokyo,Tiffin', '#3a0f1a,#8a2438,#ffd2a1'),
    ('nizhal-kalam', 'Nizhal Kalam', 'A', 146, 'Thriller,Mystery', 'Malayalam,Tamil,Telugu', '2D', current_date + 40, 'COMING_SOON', null, '12.9K',
     'A forensic sketch artist in Kochi starts drawing the faces of crimes that haven''t happened yet.',
     null, null, 'mirror', 'EVERY FACE TELLS', 'Nizhal,Kalam', '#0b0d10,#23282f,#d8dde3'),
    ('bengaluru-blues', 'Bengaluru Blues', 'UA', 122, 'Musical,Drama', 'Kannada,English', '2D', current_date + 54, 'COMING_SOON', null, '6.4K',
     'A burned-out product manager rejoins her college band for one last gig on Church Street — the same night her startup goes public.',
     null, null, 'skyline', 'ONE LAST GIG', 'Bengaluru,Blues', '#1d0f06,#6b2d0a,#ffb347');

insert into cast_members (movie_id, position, name, role, crew) values
    ('monsoon-protocol', 1, 'Arjun Malhotra', 'Insp. Vikram Rane', false),
    ('monsoon-protocol', 2, 'Sana Qureshi', 'Meera Iyer', false),
    ('monsoon-protocol', 3, 'Kabir Sethi', 'Rudra', false),
    ('monsoon-protocol', 4, 'Nandini Rao', 'DCP Kavita Desai', false),
    ('monsoon-protocol', 5, 'Imran Siddiqui', 'Lobo', false),
    ('monsoon-protocol', 6, 'Rohan Kapadia', 'Director', true),
    ('monsoon-protocol', 7, 'Aditi Sen', 'Music', true),
    ('monsoon-protocol', 8, 'Farhan Mistry', 'Cinematography', true),
    ('orbit-of-ashes', 1, 'Tara Fernandes', 'Capt. Ila Varma', false),
    ('orbit-of-ashes', 2, 'Dev Sharma', 'Koshy', false),
    ('orbit-of-ashes', 3, 'Maya Lindqvist', 'Dr. Ren', false),
    ('orbit-of-ashes', 4, 'Samir Khanna', 'Halden', false),
    ('orbit-of-ashes', 5, 'Priya Menon', 'Voice of ORCA', false),
    ('orbit-of-ashes', 6, 'Vikrant Bose', 'Director', true),
    ('orbit-of-ashes', 7, 'Lena Ortiz', 'Writer', true),
    ('iravu-vettai', 1, 'Karthik Selvan', 'Muthu', false),
    ('iravu-vettai', 2, 'Anjali Raghavan', 'SI Revathi', false),
    ('iravu-vettai', 3, 'Bharath Kumar', 'Dorai', false),
    ('iravu-vettai', 4, 'Kavya Murugan', 'Selvi', false),
    ('iravu-vettai', 5, 'M. Senthil', 'Director', true),
    ('iravu-vettai', 6, 'Ganesh Iyer', 'Music', true),
    ('chandamama-express', 1, 'Srikanth Yelamanchi', 'Srinu', false),
    ('chandamama-express', 2, 'Sowmya Reddy', 'Padma', false),
    ('chandamama-express', 3, 'Subbarao Kandula', 'Thatha', false),
    ('chandamama-express', 4, 'Keerthi Nair', 'Bujji', false),
    ('chandamama-express', 5, 'Anil Kodali', 'Director', true),
    ('chandamama-express', 6, 'Sai Charan', 'Music', true),
    ('hampi-nights', 1, 'Chethan Gowda', 'Siddhu', false),
    ('hampi-nights', 2, 'Aishwarya Hegde', 'Nila', false),
    ('hampi-nights', 3, 'Nagaraj Kulkarni', 'Appaji', false),
    ('hampi-nights', 4, 'Shruthi Rao', 'Director', true),
    ('hampi-nights', 5, 'Pradeep Acharya', 'Music', true),
    ('kaayal-kinavu', 1, 'Abin Kurian', 'Joby', false),
    ('kaayal-kinavu', 2, 'Meera Varghese', 'Aleena', false),
    ('kaayal-kinavu', 3, 'Unnikrishnan P.', 'Kuttan', false),
    ('kaayal-kinavu', 4, 'Reshma Nair', 'Director', true),
    ('kaayal-kinavu', 5, 'Jithin Paul', 'Music', true),
    ('the-last-projectionist', 1, 'Subrata Ghosh', 'Nimai', false),
    ('the-last-projectionist', 2, 'Moumita Sen', 'Mili', false),
    ('the-last-projectionist', 3, 'Arnab Dutta', 'Tapan', false),
    ('the-last-projectionist', 4, 'Kaushik Roy', 'Director', true),
    ('the-last-projectionist', 5, 'Anupam Das', 'Music', true),
    ('haveli-no-13', 1, 'Mohit Chawla', 'Bunty', false),
    ('haveli-no-13', 2, 'Chitra Bhalla', 'Chinki', false),
    ('haveli-no-13', 3, 'Om Prakash Tiwari', 'Thakur Sahab (ghost)', false),
    ('haveli-no-13', 4, 'Neha Joshi', 'Director', true),
    ('samudra-manthan-part-one', 1, 'Aditya Varma', 'Ferryman Neel', false),
    ('samudra-manthan-part-one', 2, 'Ishani Shetty', 'Mohini', false),
    ('samudra-manthan-part-one', 3, 'Raghunath Iyer', 'Vasuki (voice)', false),
    ('samudra-manthan-part-one', 4, 'S. Rajendra', 'Director', true),
    ('tokyo-tiffin', 1, 'Mira Kulkarni', 'Chhavi (voice)', false),
    ('tokyo-tiffin', 2, 'Kenji Arora', 'Taro (voice)', false),
    ('tokyo-tiffin', 3, 'Aarti Deshpande', 'Director', true),
    ('nizhal-kalam', 1, 'Alan George', 'Sketch artist Abel', false),
    ('nizhal-kalam', 2, 'Sreelakshmi Pillai', 'CI Sreeja', false),
    ('nizhal-kalam', 3, 'Binoy Mathew', 'Director', true),
    ('bengaluru-blues', 1, 'Sharanya Bhat', 'Anu', false),
    ('bengaluru-blues', 2, 'Nikhil Rao', 'Vicky', false),
    ('bengaluru-blues', 3, 'Joel D''Souza', 'Joe', false),
    ('bengaluru-blues', 4, 'Harsha Murthy', 'Director', true);

insert into food_items (id, name, size_label, price, art, tag, sort_order) values
    ('salted-popcorn', 'Salted Popcorn', 'Regular · 90g', 290, 'popcorn', 'Bestseller', 1),
    ('caramel-popcorn', 'Caramel Popcorn', 'Large · 150g', 420, 'caramel', null, 2),
    ('cola', 'Cola', '500 ml', 190, 'cola', null, 3),
    ('nachos', 'Nachos with Cheese', 'Regular', 310, 'nachos', null, 4),
    ('movie-combo', 'Movie Combo', 'Popcorn + 2 Colas', 560, 'combo', 'Save ₹110', 5),
    ('cold-coffee', 'Cold Coffee', '350 ml', 240, 'coffee', null, 6),
    ('samosa', 'Samosa', '2 pieces', 160, 'samosa', null, 7),
    ('brownie', 'Chocolate Brownie', '1 piece', 220, 'brownie', null, 8);

insert into coupons (code, label, kind, amount, max_discount, first_booking_only) values
    ('GGTFIRST', '20% off tickets, up to ₹150', 'TICKET_PERCENT', 20, 150, true),
    ('POPCORN50', '₹50 off food & beverages', 'FNB_FLAT', 50, null, false);
